# Generated by Django 2.1.2 on 2018-10-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=20, verbose_name='媒体文件类型')),
                ('title', models.CharField(max_length=40, verbose_name='素材标题')),
                ('introduction', models.CharField(max_length=100, verbose_name='素材简介')),
                ('media_id', models.CharField(max_length=200, verbose_name='素材id')),
            ],
            options={
                'db_table': 'material',
            },
        ),
    ]
